routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\UserController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return redirect()->intended(route('login', absolute: false));
});

Route::get('/dashboard', function () {
    if (Auth::user()->hasRole('admin')) {
        return redirect()->intended(route('admin.home', absolute: false));
    } else if (Auth::user()->hasRole('user')) {
        return redirect()->intended(route('user.home', absolute: false));
    }
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware(['auth', 'role.redirect'])->group(function () {

    Route::prefix('user')->as('user.')->middleware(['role:user'])->group(function () {
        Route::get('/home', [UserController::class, 'index'])->name('home');
        Route::get('/topup/index', [UserController::class, 'topup_index'])->name('topup.index');
        Route::get('/transfer/index', [UserController::class, 'transfer_index'])->name('transfer.index');
        Route::get('/transfer',[UserController::class, 'transfer'])->name('transfer');
        Route::post('/transfer',[UserController::class, 'transfer_store'])->name('transfer.store');
        Route::get('/topup', [UserController::class, 'topup'])->name('topup');
        Route::post('/topup', [UserController::class, 'topup_store'])->name('topup.store');
    });

    Route::prefix('admin')->as('admin.')->middleware(['role:admin'])->group(function () {
        Route::get('/home', [AdminController::class, 'index'])->name('home');
        Route::get('/topup', [AdminController::class, 'topup'])->name('topup.index');
        Route::patch('/topup/{id}/confirmed', [AdminController::class, 'topup_store'])->name('topup.store');
    });

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

resources/views/page/user-dashboard/home.blade.php
@extends('layout.app')

@section('page-link', '/')
@section('page-title', 'Dashboard')
@section('sub-page-title', 'Dashboard')

@section('content')
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5">
    <x-home.card-mini title="Balance" prefix="" counterValue="Rp. {{number_format($balance, 0, ',', '.')}}" suffix="" color="green" valueChanged="+ $20.9k" information="Since last week"/>
</div>
@endsection

resources/views/page/user-dashboard/topup-index.blade.php
@extends('layout.app')


@section('page-link', route('user.home'))
@section('page-title', 'User')
@section('sub-page-title', 'Top Up')

@section('content')
    <x-util.card title="Daftar Top Up" add url="{{route('user.topup')}}" custom-text="Request">
        <table id="datatable" class="table w-full pt-4 text-gray-700 dark:text-zinc-100 datatables-target-exec">
            <thead>
                <tr>
                    <th class="p-4 pr-8 border rtl:border-l-0 border-y-2 border-gray-50 dark:border-zinc-600">Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Trx Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Jumlah (Rp. )</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Status</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </x-util.card>
@endsection

@section('custom-footer')
<x-datatables.single url="{{route('user.topup.index')}}">
    <x-datatables.column name="trx_id"/>
    <x-datatables.column name="amount"/>
    <x-datatables.column name="status"/>
</x-datatables.single>
@endsection

resources/views/page/user-dashboard/topup.blade.php
@extends('layout.app')

@section('page-link', route('user.home'))
@section('page-title', 'User')
@section('sub-page-title', 'Top Up')

@section('content')
    <x-util.card title="User Top Up">
        <x-form.base url="{{ route('user.topup.store') }}" method="POST">
            <x-form.input oninput="this.value = this.value.replace(/^[._]+|[._]+$|[^0-9_.]/g, '')" name="amount"
                type="number" label="Jumlah" placeholder="input the amount" value="" />
            <x-form.input accept="image/*" texting="Image" name="proof" type="file" label="Bukti Bayar" placeholder=""
                value="" />
            <div class="mb-4 hidden" id="thumbnailContainer">
                <img id="thumbnail" src="" alt="Thumbnail" class="max-w-xs mb-2">
                <button type="button" id="removeButton"
                    class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded">Remove Image</button>
            </div>
            <x-button.submit />
            <x-button.cancel url="{{ route('user.home') }}" />
        </x-form.base>
    </x-util.card>
@endsection


@section('custom-footer')
    <script>
        // Select the file input element
        const imageFileInput = document.getElementById('input-proof');
        // Select the thumbnail container element
        const thumbnailContainer = document.getElementById('thumbnailContainer');
        // Select the thumbnail element
        const thumbnail = document.getElementById('thumbnail');
        // Select the remove button element
        const removeButton = document.getElementById('removeButton');

        // When a file is selected
        imageFileInput.addEventListener('change', function(event) {
            // Get the selected file
            const file = event.target.files[0];

            // Check if a file is selected
            if (file) {
                // Show the thumbnail container
                thumbnailContainer.classList.remove('hidden');

                // Create a FileReader object
                const reader = new FileReader();

                // When the FileReader has finished reading the file
                reader.onload = function(e) {
                    // Set the thumbnail source as the result of the FileReader
                    thumbnail.setAttribute('src', e.target.result);
                };

                // Read the file as a data URL
                reader.readAsDataURL(file);
            } else {
                // Hide the thumbnail container if no file is selected
                thumbnailContainer.classList.add('hidden');
            }
        });

        // When the remove button is clicked
        removeButton.addEventListener('click', function() {
            // Reset the file input value
            imageFileInput.value = '';
            // Hide the thumbnail container
            thumbnailContainer.classList.add('hidden');
        });
    </script>
@endsection

resources/views/page/user-dashboard/transfer-index.blade.php
@extends('layout.app')


@section('page-link', route('user.home'))
@section('page-title', 'User')
@section('sub-page-title', 'Transfer')

@section('content')
    <x-util.card title="Daftar Transfer" add url="{{route('user.transfer')}}" custom-text="Transfer">
        <table id="datatable" class="table w-full pt-4 text-gray-700 dark:text-zinc-100 datatables-target-exec">
            <thead>
                <tr>
                    <th class="p-4 pr-8 border rtl:border-l-0 border-y-2 border-gray-50 dark:border-zinc-600">Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Trx Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Transaksi</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Dari/Ke</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Nominal</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Keterangan</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Status</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Waktu</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </x-util.card>
@endsection

@section('custom-footer')
<x-datatables.single url="{{route('user.transfer.index')}}">
    <x-datatables.column name="trx_id"/>
    <x-datatables.column name="type_transaction.name"/>
    <x-datatables.column name="direction_user_name"/>
    <x-datatables.column name="amount"/>
    <x-datatables.column name="transaction_detail.notes"/>
    <x-datatables.column name="status"/>
    <x-datatables.column name="created_at"/>
</x-datatables.single>
@endsection

resources/views/page/user-dashboard/transfer.blade.php
@extends('layout.app')

@section('page-link', route('user.home'))
@section('page-title', 'User')
@section('sub-page-title', 'Transfer')

@section('content')
    <x-util.card title="User Transfer">
        <x-form.base url="{{ route('user.transfer.store') }}" method="POST">
            <x-form.input oninput="this.value = this.value.replace(/[^a-zA-Z0-9@_.]/g, '');" name="email" type="email" label="Email" placeholder="input the email" value="" />
            <x-form.input oninput="this.value = this.value.replace(/^[._]+|[._]+$|[^0-9_.]/g, '')" name="amount" type="number" label="Jumlah" placeholder="input the amount" value="" />
            <x-form.input name="notes" type="text" label="Keterangan" placeholder="input the notes" value="" />
            <x-button.submit />
            <x-button.cancel url="{{ route('user.home') }}" />
        </x-form.base>
    </x-util.card>
@endsection