routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\UserController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return redirect()->intended(route('login', absolute: false));
});

Route::get('/dashboard', function () {
    if (Auth::user()->hasRole('admin')) {
        return redirect()->intended(route('admin.home', absolute: false));
    } else if (Auth::user()->hasRole('user')) {
        return redirect()->intended(route('user.home', absolute: false));
    }
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware(['auth', 'role.redirect'])->group(function () {

    Route::prefix('user')->as('user.')->middleware(['role:user'])->group(function () {
        Route::get('/home', [UserController::class, 'index'])->name('home');
        Route::get('/topup/index', [UserController::class, 'topup_index'])->name('topup.index');
        Route::get('/transfer/index', [UserController::class, 'transfer_index'])->name('transfer.index');
        Route::get('/transfer',[UserController::class, 'transfer'])->name('transfer');
        Route::post('/transfer',[UserController::class, 'transfer_store'])->name('transfer.store');
        Route::get('/topup', [UserController::class, 'topup'])->name('topup');
        Route::post('/topup', [UserController::class, 'topup_store'])->name('topup.store');
    });

    Route::prefix('admin')->as('admin.')->middleware(['role:admin'])->group(function () {
        Route::get('/home', [AdminController::class, 'index'])->name('home');
        Route::get('/topup', [AdminController::class, 'topup'])->name('topup.index');
        Route::patch('/topup/{id}/confirmed', [AdminController::class, 'topup_store'])->name('topup.store');
    });

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

resources/views/page/admin-dashboard/admin/home.blade.php
@extends('layout.app')

@section('page-link', '/')
@section('page-title', 'Dashboard')
@section('sub-page-title', 'Dashboard')

@section('content')
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5">
    <x-home.card-mini title="Total Balance User" prefix="" counterValue="{{number_format($data['all_balance'], 0, ',', '.')}}" suffix="" color="" valueChanged="" information="Since last week"/>
    <x-home.card-mini title="Total User" prefix="" counterValue="{{$data['all_user']}}" suffix="" color="" valueChanged="" information="Since last week"/>
</div>
@endsection

resources/views/page/admin-dashboard/admin/index.blade.php
@extends('layout.app')


@section('page-link', route('admin.admin.index'))
@section('page-title', 'Data')
@section('sub-page-title', 'Admin')

@section('content')
    <x-util.card title="Admin" add url="{{route('admin.admin.create')}}">
        <table id="datatable" class="table w-full pt-4 text-gray-700 dark:text-zinc-100 datatables-target-exec">
            <thead>
                <tr>
                    <th class="p-4 pr-8 border rtl:border-l-0 border-y-2 border-gray-50 dark:border-zinc-600">Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Name</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Email</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Username</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Role</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Action</th>
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </x-util.card>
@endsection

@section('custom-footer')
<x-datatables.single url="{{route('admin.admin.index')}}">
    <x-datatables.column name="name"/>
    <x-datatables.column name="email"/>
    <x-datatables.column name="username"/>
    <x-datatables.column name="role"/>
    <x-datatables.action />
</x-datatables.single>
@endsection

resources/views/page/admin-dashboard/admin/topup.blade.php
@extends('layout.app')


@section('page-link', route('admin.home'))
@section('page-title', 'Data')
@section('sub-page-title', 'Admin')

@section('content')
    <x-util.card title="Admin">
        <table id="datatable" class="table w-full pt-4 text-gray-700 dark:text-zinc-100 datatables-target-exec">
            <thead>
                <tr>
                    <th class="p-4 pr-8 border rtl:border-l-0 border-y-2 border-gray-50 dark:border-zinc-600">Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Trx Id</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Name</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Nominal</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Proof</th>
                    <th class="p-4 pr-8 border border-y-2 border-gray-50 dark:border-zinc-600 border-l-0">Action</th>
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </x-util.card>
@endsection

@section('custom-footer')
<x-datatables.single url="{{route('admin.topup.index')}}">
    <x-datatables.column name="trx_id"/>
    <x-datatables.column name="user.name"/>
    <x-datatables.column name="amount"/>
    <x-datatables.column name="proof"/>
    <x-datatables.action />
</x-datatables.single>
@endsection